
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 17 21:53:10 BRT 2017
//----------------------------------------------------

package compiler.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTO = 13;
  public static final int DIFERENTE_QUE = 4;
  public static final int KEY_CHAR = 33;
  public static final int MULT = 11;
  public static final int CHAR_LITERAL = 26;
  public static final int SOMA = 9;
  public static final int ABRE_CHAVE = 22;
  public static final int FECHA_CHAVE = 23;
  public static final int VIRGULA = 18;
  public static final int IDENTIFICADOR = 2;
  public static final int MENOR_OU_IGUAL = 8;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int ABRE_PAR = 20;
  public static final int OR = 15;
  public static final int KEY_WHILE = 29;
  public static final int KEY_VAR = 35;
  public static final int KEY_FLOAT = 32;
  public static final int DIV = 12;
  public static final int FECHA_PAR = 21;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 19;
  public static final int error = 1;
  public static final int KEY_PRINT = 34;
  public static final int MAIOR_QUE = 5;
  public static final int KEY_INT = 31;
  public static final int KEY_RETURN = 30;
  public static final int KEY_ELSE = 28;
  public static final int IGUAL_QUE = 3;
  public static final int MAIOR_OU_IGUAL = 7;
  public static final int KEY_IF = 27;
  public static final int KEY_PROC = 36;
  public static final int ATRIBUICAO = 17;
  public static final int MENOR_QUE = 6;
  public static final int FLOAT_LITERAL = 25;
  public static final int SUB = 10;
  public static final int INT_LITERAL = 24;
}

